library(slidify)

slidify("index.Rmd")
slidify("ch00-introduction.Rmd")
slidify("ch01-worlds-of-dbms.Rmd")
slidify("ch02-relational-model.Rmd")
slidify("ch03-design-theory.Rmd")
slidify("ch04-high-level-models.Rmd")
slidify("exam1-results.Rmd")
slidify("ch05-query-languages.Rmd")
slidify("ch06-sql.Rmd")
slidify("ch07-constraints-triggers.Rmd")
slidify("ch08-views-indexes.Rmd")
slidify("ch09-db-programming.Rmd")
